name: TODO Continuous Integration (Layer)

# The `aws-actions/aws-lambda-deploy@v1` does not support deploying layers at time of writing (2025-08-30).
# So we still have to go back to use AWS CLI for that.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Deploy AWS Lambda
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v4

      - name: List files (for debugging)
        run: ls -R

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          $layer_name = 'postgres'
          Set-Variable temp_layer_folder_path -Option Constant -Value '${{ vars.LAMBDA_LAYER_BUILD_FOLDER_PATH }}'
          $pip_output_path = Join-Path $temp_layer_folder_path "$layer_name/python"
          New-Item -ItemType Directory -Path $pip_output_path
          $layer_requirements_path = Join-Path '${{ vars.LAMBDA_LAYER_SRC_FOLDER_PATH }}' "$($layer_name)_layer_requirements.txt"
          Write-Host $layer_requirements_path
          pip install -r $layer_requirements_path --platform manylinux2014_x86_64 --target $pip_output_path --only-binary=:all: psycopg2-binary
          pip freeze

          Compress-Archive $pip_output_path -DestinationPath '${{ vars.LAMBDA_LAYER_ZIP_FILE_PATH }}' -Force

      - name: Create AWS Lambda Function artifact
        uses: actions/upload-artifact@v4
        with:
          name: aws-lambda-layer                  # Name of the artifact (aws-lambda-layer.zip)
          path: |                                 # Note: Use unix style path (./). Does not work with Windows style path (.\).
            ${{ vars.LAMBDA_LAYER_BUILD_FOLDER_PATH }}

      - name: Deploy AWS Lambda Layer
        run: |
          $layer_name = 'postgres_layer'
          $ZipFilePath = '${{ vars.LAMBDA_LAYER_ZIP_FILE_PATH }}'
          aws lambda publish-layer-version `
          --layer-name $layer_name `
          --zip-file fileb://$ZipFilePath `
          --description "Layer for interacting with Postgres" `
          --compatible-runtimes python3.10 `
          --compatible-architectures x86_64 `
          --license-info AGPL-3.0-or-later

      - name: List files (for debugging)
        run: ls -R
